source "https://rubygems.org"
# Replace 4.3.2 with the version of Foundation you want to use
gem "zurb-foundation", "4.3.2"
#gem "compass"
#set Compass and SASS to versions that don't produce errors
gem "compass" , "0.12.6"
gem "sass", "3.2.19"
# gem "guard"
# For more information on this file see:
# http://foundation.zurb.com/docs/sass.html
# http://zslabs.com/articles/versioned-dependencies-with-compass 